### ISSUE TITLE
Can't install pdfextract

### ISSUE THREAD

**Issue by teto** [CrossRef/pdfextract#10]
Hi,

if I try to install via gem (gem2.0 or gem1.9) , I have this error:
# 

% sudo gem install pdf-extract           ±[master]
Building native extensions.  This could take a while...
ERROR:  Error installing pdf-extract:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

creating Makefile

make
# compiling libsvm_wrap.cxx

and if I try to build the program myself with rake, I have:
# 

rake2.0 build                          ±[master]
rake aborted!
cannot load such file -- libsvm
/home/teto/pdfextract/lib/pdf/extract/references/score.rb:1:in `<top (required)>'
/home/teto/pdfextract/lib/pdf/extract/references/references.rb:3:in`require_relative'
/home/teto/pdfextract/lib/pdf/extract/references/references.rb:3:in `<top (required)>'
/home/teto/pdfextract/lib/pdf/extract.rb:10:in`require_relative'
/home/teto/pdfextract/lib/pdf/extract.rb:10:in `<top (required)>'
/home/teto/pdfextract/lib/pdf-extract.rb:1:in`require_relative'
/home/teto/pdfextract/lib/pdf-extract.rb:1:in `<top (required)>'
/home/teto/pdfextract/tasks/assign.rb:3:in`require_relative'
/home/teto/pdfextract/tasks/assign.rb:3:in `<top (required)>'
/home/teto/pdfextract/Rakefile:1:in`require_relative'
# /home/teto/pdfextract/Rakefile:1:in `<top (required)>'

Any idea ?

REgards

**Comment by abitofalchemy** [comment]
I have a system that after 'sudo apt-get upgrade ruby' I still ended up with:
ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [i686-linux]

Do I need to move to a 64bit system?
